// <auto-generated />

using Microsoft.FeatureManagement;
using Stravaig.FeatureFlags;

public interface IAlphaFeatureFlag : IStronglyTypedFeatureFlag
{
}

public sealed class AlphaFeatureFlag : StronglyTypedFeatureFlag, IAlphaFeatureFlag
{
    public AlphaFeatureFlag(IFeatureManager featureManager)
        : base(featureManager, "Alpha")
    {
    }
}

public interface IBetaFeatureFlag : IStronglyTypedFeatureFlag
{
}

public sealed class BetaFeatureFlag : StronglyTypedFeatureFlag, IBetaFeatureFlag
{
    public BetaFeatureFlag(IFeatureManager featureManager)
        : base(featureManager, "Beta")
    {
    }
}

public interface IGammaFeatureFlag : IStronglyTypedFeatureFlag
{
}

public sealed class GammaFeatureFlag : StronglyTypedFeatureFlag, IGammaFeatureFlag
{
    public GammaFeatureFlag(IFeatureManager featureManager)
        : base(featureManager, "Gamma")
    {
    }
}


public static class MyFeaturesServiceExtensions
{
    public static IFeatureManagementBuilder AddStronglyTypedMyFeatures(this IFeatureManagementBuilder builder)
    {
        builder.Services.AddScoped<IAlphaFeatureFlag, AlphaFeatureFlag>();
        builder.Services.AddScoped<IBetaFeatureFlag, BetaFeatureFlag>();
        builder.Services.AddScoped<IGammaFeatureFlag, GammaFeatureFlag>();
        return builder;
    }
}