//HintName: My.Test.Namespace.FeatureFlagNames.g.cs
// <auto-generated />
// Namespace: My.Test.Namespace
// Enum: FeatureFlagNames
// IncludeTestFakes: True
// FeatureFlagNames[0]: FeatureOne
// FeatureFlagNames[1]: FeatureTwo

namespace My.Test.Namespace
{
    public interface IFeatureOneFeatureFlag : Stravaig.FeatureFlags.IStronglyTypedFeatureFlag
    {
    }

    public sealed class FeatureOneFeatureFlag : Stravaig.FeatureFlags.FeatureFlag, IFeatureOneFeatureFlag
    {
        public FeatureOneFeatureFlag(Microsoft.FeatureManagement.IFeatureManager featureManager)
            : base(featureManager, "FeatureOne")
        {
        }
    }

    public interface IFeatureTwoFeatureFlag : Stravaig.FeatureFlags.IStronglyTypedFeatureFlag
    {
    }

    public sealed class FeatureTwoFeatureFlag : Stravaig.FeatureFlags.FeatureFlag, IFeatureTwoFeatureFlag
    {
        public FeatureTwoFeatureFlag(Microsoft.FeatureManagement.IFeatureManager featureManager)
            : base(featureManager, "FeatureTwo")
        {
        }
    }

}
