//HintName: My.Test.Namespace.Testing.FeatureFlags.g.cs
// <auto-generated />

using Microsoft.FeatureManagement;
using Stravaig.FeatureFlag;

namespace My.Test.Namespace.Testing
{

    public sealed class FakeFeatureOneFeatureFlag : IFeatureOneFeatureFlag
    {
        public static readonly FakeFeatureOneFeatureFlag Enabled = new (true);
        public static readonly FakeFeatureOneFeatureFlag Disabled = new (false);

        private readonly bool _state;
        public FakeFeatureOneFeatureFlag(bool state)
        {
            _state = state;
        }

        public Task<bool> IsEnabledAsync() => Task.FromResult(_state);

        public bool IsEnabled() => _state;
    }


    public sealed class FakeFeatureTwoFeatureFlag : IFeatureTwoFeatureFlag
    {
        public static readonly FakeFeatureTwoFeatureFlag Enabled = new (true);
        public static readonly FakeFeatureTwoFeatureFlag Disabled = new (false);

        private readonly bool _state;
        public FakeFeatureTwoFeatureFlag(bool state)
        {
            _state = state;
        }

        public Task<bool> IsEnabledAsync() => Task.FromResult(_state);

        public bool IsEnabled() => _state;
    }

}
