//HintName: My.Test.Namespace.Testing.FeatureFlags.g.cs
// <auto-generated />

using Microsoft.FeatureManagement;
using Stravaig.FeatureFlags;

namespace My.Test.Namespace.Testing
{

    public sealed class FakeFeatureOneFeatureFlag : Stravaig.FeatureFlags.Testing.FakeFeatureFlag, IFeatureOneFeatureFlag
    {
        public static readonly FakeFeatureOneFeatureFlag Enabled = new FakeFeatureOneFeatureFlag(true);
        public static readonly FakeFeatureOneFeatureFlag Disabled = new FakeFeatureOneFeatureFlag(false);

        public FakeFeatureOneFeatureFlag(bool state) : base(state)
        {
        }
    }


    public sealed class FakeFeatureTwoFeatureFlag : Stravaig.FeatureFlags.Testing.FakeFeatureFlag, IFeatureTwoFeatureFlag
    {
        public static readonly FakeFeatureTwoFeatureFlag Enabled = new FakeFeatureTwoFeatureFlag(true);
        public static readonly FakeFeatureTwoFeatureFlag Disabled = new FakeFeatureTwoFeatureFlag(false);

        public FakeFeatureTwoFeatureFlag(bool state) : base(state)
        {
        }
    }

}
