//HintName: My.Test.Namespace.FeatureFlags.g.cs
// <auto-generated />

using Microsoft.Extensions.DependencyInjection;
using Microsoft.FeatureManagement;
using Stravaig.FeatureFlags;

namespace My.Test.Namespace;
public interface ITheTransientFeatureFeatureFlag : Stravaig.FeatureFlags.IStronglyTypedFeatureFlag
{
}

public sealed class TheTransientFeatureFeatureFlag : Stravaig.FeatureFlags.FeatureFlag, ITheTransientFeatureFeatureFlag
{
    public TheTransientFeatureFeatureFlag(IFeatureManager featureManager)
        : base(featureManager, "TheTransientFeature")
    {
    }
}

public interface ITheScopedFeatureFeatureFlag : Stravaig.FeatureFlags.IStronglyTypedFeatureFlag
{
}

public sealed class TheScopedFeatureFeatureFlag : Stravaig.FeatureFlags.FeatureFlag, ITheScopedFeatureFeatureFlag
{
    public TheScopedFeatureFeatureFlag(IFeatureManager featureManager)
        : base(featureManager, "TheScopedFeature")
    {
    }
}

public interface ITheSingletonFeatureFeatureFlag : Stravaig.FeatureFlags.IStronglyTypedFeatureFlag
{
}

public sealed class TheSingletonFeatureFeatureFlag : Stravaig.FeatureFlags.FeatureFlag, ITheSingletonFeatureFeatureFlag
{
    public TheSingletonFeatureFeatureFlag(IFeatureManager featureManager)
        : base(featureManager, "TheSingletonFeature")
    {
    }
}

public interface ITheDefaultFeatureFeatureFlag : Stravaig.FeatureFlags.IStronglyTypedFeatureFlag
{
}

public sealed class TheDefaultFeatureFeatureFlag : Stravaig.FeatureFlags.FeatureFlag, ITheDefaultFeatureFeatureFlag
{
    public TheDefaultFeatureFeatureFlag(IFeatureManager featureManager)
        : base(featureManager, "TheDefaultFeature")
    {
    }
}


public static class FeatureFlagsServiceExtensions
{
    public static IFeatureManagementBuilder AddFeatureFlags(this IFeatureManagementBuilder builder)
    {
        builder.Services.AddTransient<ITheTransientFeatureFeatureFlag, TheTransientFeatureFeatureFlag>();
        builder.Services.AddScoped<ITheScopedFeatureFeatureFlag, TheScopedFeatureFeatureFlag>();
        builder.Services.AddSingleton<ITheSingletonFeatureFeatureFlag, TheSingletonFeatureFeatureFlag>();
        builder.Services.AddScoped<ITheDefaultFeatureFeatureFlag, TheDefaultFeatureFeatureFlag>();
        return builder;
    }
}
